// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pessoa_juridica.sql

package pgstore

import (
	"context"
)

const consultarSaldoPessoaJuridica = `-- name: ConsultarSaldoPessoaJuridica :one
SELECT saldo FROM pessoa_juridica WHERE id = $1
`

func (q *Queries) ConsultarSaldoPessoaJuridica(ctx context.Context, id int32) (string, error) {
	row := q.db.QueryRow(ctx, consultarSaldoPessoaJuridica, id)
	var saldo string
	err := row.Scan(&saldo)
	return saldo, err
}

const criarPessoaJuridica = `-- name: CriarPessoaJuridica :one
INSERT INTO pessoa_juridica (
  faturamento,
  idade,
  nome_fantasia,
  celular,
  email_corporativo,
  categoria
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id
`

type CriarPessoaJuridicaParams struct {
	Faturamento      string `json:"faturamento"`
	Idade            int32  `json:"idade"`
	NomeFantasia     string `json:"nome_fantasia"`
	Celular          string `json:"celular"`
	EmailCorporativo string `json:"email_corporativo"`
	Categoria        string `json:"categoria"`
}

func (q *Queries) CriarPessoaJuridica(ctx context.Context, arg CriarPessoaJuridicaParams) (int32, error) {
	row := q.db.QueryRow(ctx, criarPessoaJuridica,
		arg.Faturamento,
		arg.Idade,
		arg.NomeFantasia,
		arg.Celular,
		arg.EmailCorporativo,
		arg.Categoria,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
