// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pessoa_fisica.sql

package pgstore

import (
	"context"
)

const consultarSaldoPessoaFisica = `-- name: ConsultarSaldoPessoaFisica :one
SELECT saldo FROM pessoa_fisica WHERE id = $1
`

func (q *Queries) ConsultarSaldoPessoaFisica(ctx context.Context, id int32) (string, error) {
	row := q.db.QueryRow(ctx, consultarSaldoPessoaFisica, id)
	var saldo string
	err := row.Scan(&saldo)
	return saldo, err
}

const criarPessoaFisica = `-- name: CriarPessoaFisica :one
INSERT INTO pessoa_fisica (
  renda_mensal,
  idade,
  nome_completo,
  celular,
  email,
  categoria
) VALUES (
  $1, $2, $3, $4, $5, $6
) RETURNING id
`

type CriarPessoaFisicaParams struct {
	RendaMensal  string `json:"renda_mensal"`
	Idade        int32  `json:"idade"`
	NomeCompleto string `json:"nome_completo"`
	Celular      string `json:"celular"`
	Email        string `json:"email"`
	Categoria    string `json:"categoria"`
}

func (q *Queries) CriarPessoaFisica(ctx context.Context, arg CriarPessoaFisicaParams) (int32, error) {
	row := q.db.QueryRow(ctx, criarPessoaFisica,
		arg.RendaMensal,
		arg.Idade,
		arg.NomeCompleto,
		arg.Celular,
		arg.Email,
		arg.Categoria,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
