// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pgstore

import (
	"context"
)

type Querier interface {
	ConsultarSaldoPessoaFisica(ctx context.Context, id int32) (string, error)
	ConsultarSaldoPessoaJuridica(ctx context.Context, id int32) (string, error)
	CriarPessoaFisica(ctx context.Context, arg CriarPessoaFisicaParams) (int32, error)
	CriarPessoaJuridica(ctx context.Context, arg CriarPessoaJuridicaParams) (int32, error)
}

var _ Querier = (*Queries)(nil)
